import type {
  MasterShootDNA,
  RecommendedShot,
  LookbookInput,
} from "./types";
import {
  PRODUCT_FAMILY_LABELS,
  STYLE_LABELS,
  GOAL_LABELS,
  GENDER_LABELS,
  LOGO_LABELS,
  CREATIVITY_LABELS,
} from "./types";

export function formatExportText(
  dna: MasterShootDNA,
  shots: RecommendedShot[],
  generationOrder: number[],
  input: LookbookInput
): string {
  const lines: string[] = [];

  lines.push("LOOKBOOK STUDIO PLAN");
  lines.push("====================");
  lines.push("");

  // Master Shoot DNA
  lines.push("Master Shoot DNA");
  lines.push("-----------------");
  lines.push(`Campaign direction: ${dna.campaignDirection}`);
  lines.push(
    `Product: ${dna.specificItem ? `${dna.specificItem} (${PRODUCT_FAMILY_LABELS[dna.productFamily]})` : PRODUCT_FAMILY_LABELS[dna.productFamily]}`
  );
  lines.push(`Gender: ${GENDER_LABELS[dna.genderPresentation]}`);
  lines.push(`Style: ${STYLE_LABELS[dna.targetStyle]}`);
  lines.push(`Goal: ${GOAL_LABELS[dna.campaignGoal]}`);
  lines.push(`Logo priority: ${LOGO_LABELS[dna.logoVisibilityPriority]}`);
  lines.push(`Creativity: ${CREATIVITY_LABELS[dna.creativityLevel]}`);
  lines.push("");
  lines.push(`Environment: ${dna.environmentFamily}`);
  lines.push(`Lighting: ${dna.lightingFamily}`);
  lines.push(`Lens family: ${dna.lensFamily}`);
  lines.push(`Framing family: ${dna.framingFamily}`);
  lines.push(`Motion allowance: ${dna.motionAllowance}`);
  lines.push(`Finish: ${dna.finishFamily}`);
  lines.push(`Realism: ${dna.realismProfile}`);
  lines.push(`Branding rules: ${dna.brandingVisibilityRules}`);
  lines.push("");

  // Generation order
  const firstThree = generationOrder.slice(0, 3).map((i) => `#${i + 1}`);
  lines.push(`Recommended first shots: ${firstThree.join(", ")}`);
  lines.push(`${dna.generationPriorityNotes}`);
  lines.push("");
  lines.push("---");
  lines.push("");

  // Individual shots
  for (const shot of shots) {
    lines.push(`${shot.position}. ${shot.archetype.title}`);
    lines.push(`   Role: ${shot.archetype.role}`);
    lines.push(`   Category: ${shot.archetype.shotCategory}`);
    lines.push(`   What it sells: ${shot.whatItSells}`);
    lines.push(`   Framing: ${shot.framingDelta}`);
    lines.push(`   Pose: ${shot.poseDelta}`);
    lines.push(`   Branding: ${shot.brandingSafety}`);
    lines.push(`   Reliability: ${shot.archetype.higgsfieldReliability} | Difficulty: ${shot.archetype.difficulty}`);
    lines.push(`   Priority: #${shot.generationPriority}`);
    lines.push("");
    lines.push(`   DELTA BRIEF:`);
    lines.push(`   ${shot.deltaBrief}`);
    lines.push("");
    lines.push(`   NEGATIVE CUES:`);
    lines.push(`   ${shot.negativeCues}`);
    lines.push("");
    lines.push("---");
    lines.push("");
  }

  lines.push("Generated by Lookbook Studio v1");

  return lines.join("\n");
}
