import type { ShotArchetype } from "./types";

export const ALL_ARCHETYPES: ShotArchetype[] = [
  // ────────────────────────────────────────────
  // 1. hero_full_body_seller
  // ────────────────────────────────────────────
  {
    id: "hero_full_body_seller",
    title: "Hero Full-Body Seller",
    role: "Primary product visibility shot. The anchor of every lookbook set.",
    shotCategory: "hero",
    suitableFamilies: [
      "apparel",
      "footwear",
      "bags",
      "jewelry",
      "eyewear",
      "watches",
      "headwear",
      "belts",
      "scarves",
      "small_accessories",
      "full_look",
    ],
    suitableItems: [],
    suitableGoals: ["product_clarity", "premium_branding"],
    suitableStyles: [
      "commercial",
      "editorial",
      "luxury",
      "minimal",
      "street",
      "resort",
      "tailoring",
      "contemporary",
      "avant_garde",
    ],
    suitableGenderPresentation: ["menswear", "womenswear", "unisex"],
    creativityBand: ["safe", "balanced"],
    logoVisibilitySuitability: "high",
    productClaritySuitability: "high",
    silhouetteSuitability: "medium",
    detailSuitability: "medium",
    movementSuitability: "low",
    editorialStrength: "low",
    higgsfieldReliability: "high",
    difficulty: "easy",
    logoRisk: "low",
    anatomyRisk: "low",
    occlusionRisk: "low",
    bestUsedWhen: "Every set needs one. Use as the opening shot or e-commerce hero.",
    avoidWhen: "Never skip this archetype; only deprioritise if the brief is purely editorial mood.",
    defaultFraming: "Full body, head to toe, centred in frame with breathing room at top and sides",
    defaultLens: "85mm",
    defaultAperture: "f/5.6",
    defaultCameraHeight: "chest height",
    defaultCameraDistance: "~4m",
    defaultAngle: "Straight on, camera perpendicular to model",
    defaultLighting: "Soft directional light from camera-right, gentle fill from left",
    poseFamily: "Standing neutral",
    bodyDirection: "Square to camera, shoulders facing lens",
    handBehavior: "Relaxed at sides or one hand lightly touching thigh",
    legBehavior: "Feet shoulder-width, weight evenly distributed",
    headDirection: "Straight to camera or very slight turn (5 degrees max)",
    realismNotes:
      "Higgsfield handles this reliably. Watch for: symmetrical hand rendering, ensure all fingers are visible and natural. Check garment hem is not clipped by frame edge.",
    whyItWorks:
      "Front-facing full body is the industry standard for product clarity because buyers can see the entire garment, fit, and branding in a single frame.",
    deltaBlueprint:
      "Override framing to full-body centred, head to toe. Lock camera straight-on at chest height. Model stands square to lens, weight even, hands relaxed at sides. Prioritise garment visibility over editorial mood. No rotation, no crop. This is the anchor shot.",
  },

  // ────────────────────────────────────────────
  // 2. clean_silhouette_fullbody
  // ────────────────────────────────────────────
  {
    id: "clean_silhouette_fullbody",
    title: "Clean Silhouette Full-Body",
    role: "Side-angle full-body showing garment outline and proportions.",
    shotCategory: "silhouette",
    suitableFamilies: ["apparel", "full_look"],
    suitableItems: [],
    suitableGoals: ["silhouette", "product_clarity"],
    suitableStyles: [
      "commercial",
      "editorial",
      "luxury",
      "minimal",
      "tailoring",
      "contemporary",
      "avant_garde",
    ],
    suitableGenderPresentation: ["menswear", "womenswear", "unisex"],
    creativityBand: ["safe", "balanced", "directional"],
    logoVisibilitySuitability: "medium",
    productClaritySuitability: "medium",
    silhouetteSuitability: "high",
    detailSuitability: "low",
    movementSuitability: "low",
    editorialStrength: "medium",
    higgsfieldReliability: "high",
    difficulty: "easy",
    logoRisk: "medium",
    anatomyRisk: "low",
    occlusionRisk: "low",
    bestUsedWhen:
      "The garment has a distinctive shape, drape, or proportion worth highlighting, such as oversized coats, A-line dresses, or structured blazers.",
    avoidWhen:
      "Logo placement is on the front only and must be visible, or the garment has no distinctive silhouette value.",
    defaultFraming: "Full body, head to toe, slight negative space behind model for outline clarity",
    defaultLens: "85mm",
    defaultAperture: "f/5.6",
    defaultCameraHeight: "chest height",
    defaultCameraDistance: "~4m",
    defaultAngle: "30-45 degree side angle from camera-left or camera-right",
    defaultLighting: "Soft backlight for edge separation, gentle key from opposite side to define shape",
    poseFamily: "Standing profile",
    bodyDirection: "Three-quarter turn away from camera, torso angled 30-45 degrees",
    handBehavior: "Hands down or lightly touching garment to avoid breaking the silhouette line",
    legBehavior: "Feet together or slightly staggered, one leg slightly forward for natural line",
    headDirection: "Turned toward camera 15-20 degrees, chin slightly lifted",
    realismNotes:
      "Side angles are generally reliable. Watch for: shoulder proportions at the turned angle, ensure the far arm does not merge visually with the torso. Backlit edges can sometimes glow unnaturally.",
    whyItWorks:
      "A clean silhouette reveals garment proportions, drape, and construction that a front-facing shot cannot, giving buyers a three-dimensional understanding of the piece.",
    deltaBlueprint:
      "Shift camera 30-45 degrees to side. Model turns body to three-quarter angle, head rotated slightly back toward lens. Add backlight for edge definition. Hands stay below garment outline. Full body framing with extra negative space behind the model to isolate the shape.",
  },

  // ────────────────────────────────────────────
  // 3. relaxed_contrapposto
  // ────────────────────────────────────────────
  {
    id: "relaxed_contrapposto",
    title: "Relaxed Contrapposto",
    role: "Classic S-curve standing pose with natural asymmetry and weight shift.",
    shotCategory: "hero",
    suitableFamilies: [
      "apparel",
      "footwear",
      "bags",
      "jewelry",
      "eyewear",
      "watches",
      "headwear",
      "belts",
      "scarves",
      "small_accessories",
      "full_look",
    ],
    suitableItems: [],
    suitableGoals: ["product_clarity", "premium_branding", "silhouette"],
    suitableStyles: [
      "commercial",
      "editorial",
      "luxury",
      "minimal",
      "street",
      "resort",
      "tailoring",
      "contemporary",
      "avant_garde",
    ],
    suitableGenderPresentation: ["menswear", "womenswear", "unisex"],
    creativityBand: ["safe", "balanced"],
    logoVisibilitySuitability: "high",
    productClaritySuitability: "high",
    silhouetteSuitability: "high",
    detailSuitability: "low",
    movementSuitability: "low",
    editorialStrength: "medium",
    higgsfieldReliability: "high",
    difficulty: "easy",
    logoRisk: "low",
    anatomyRisk: "low",
    occlusionRisk: "low",
    bestUsedWhen:
      "You need a natural-looking hero that feels less rigid than a straight-on seller shot while still showing the full garment clearly.",
    avoidWhen: "The brief explicitly requests symmetrical, flat product shots (catalogue style).",
    defaultFraming: "Full body, head to toe, slight asymmetric composition",
    defaultLens: "85mm",
    defaultAperture: "f/5.6",
    defaultCameraHeight: "chest height",
    defaultCameraDistance: "~4m",
    defaultAngle: "Straight on or very slight angle (5-10 degrees)",
    defaultLighting: "Soft directional light from camera-right, subtle fill, natural shadow play on fabric",
    poseFamily: "Contrapposto standing",
    bodyDirection: "Hips shifted to one side, shoulders counter-tilted, facing camera",
    handBehavior: "One hand relaxed at side, other resting lightly on hip or thigh",
    legBehavior: "Weight on one leg, other leg relaxed with knee slightly bent",
    headDirection: "Straight to camera or slight tilt matching the shoulder line",
    realismNotes:
      "Higgsfield renders contrapposto well because it is a natural human resting pose. Watch for: hip-to-waist ratio looking natural, ensure the relaxed knee does not create an odd fabric fold.",
    whyItWorks:
      "Contrapposto adds visual energy and a premium feel to what is still a product-first shot, making the garment look worn rather than displayed.",
    deltaBlueprint:
      "Keep framing and camera from hero setup. Shift model weight onto one leg, drop opposite hip, counter-tilt shoulders for S-curve. One hand rests on hip or thigh. Relaxed knee creates asymmetry. Maintain front-facing orientation for product visibility.",
  },

  // ────────────────────────────────────────────
  // 4. open_jacket_ease
  // ────────────────────────────────────────────
  {
    id: "open_jacket_ease",
    title: "Open Jacket Ease",
    role: "Jacket opened to reveal layering, interior construction, or underlying garment.",
    shotCategory: "editorial",
    suitableFamilies: ["apparel"],
    suitableItems: ["blazer", "jacket", "coat", "overcoat", "parka", "trench"],
    suitableGoals: ["styling_story", "product_clarity"],
    suitableStyles: ["editorial", "luxury", "tailoring", "contemporary", "street"],
    suitableGenderPresentation: ["menswear", "womenswear", "unisex"],
    creativityBand: ["balanced", "directional"],
    logoVisibilitySuitability: "medium",
    productClaritySuitability: "medium",
    silhouetteSuitability: "medium",
    detailSuitability: "medium",
    movementSuitability: "low",
    editorialStrength: "high",
    higgsfieldReliability: "medium",
    difficulty: "moderate",
    logoRisk: "medium",
    anatomyRisk: "low",
    occlusionRisk: "medium",
    bestUsedWhen:
      "The outer layer is the hero product and there is a deliberate layering story: shirt under blazer, turtleneck under coat, etc.",
    avoidWhen:
      "The product is a single-layer top or the inner garment is not styled. Also avoid if logo is on the front of a closed jacket.",
    defaultFraming: "Three-quarter to full body, showing the full opening of the jacket",
    defaultLens: "85mm",
    defaultAperture: "f/4",
    defaultCameraHeight: "chest height",
    defaultCameraDistance: "~3m",
    defaultAngle: "Slight angle, 10-20 degrees off centre to show jacket opening depth",
    defaultLighting: "Soft key from camera-right to illuminate interior lining and layering, gentle fill",
    poseFamily: "Standing editorial",
    bodyDirection: "Slight three-quarter turn, torso open to camera to reveal jacket interior",
    handBehavior: "One hand holding jacket open at lapel or hem, other relaxed or in pocket",
    legBehavior: "Natural stance, weight slightly shifted, feet apart",
    headDirection: "Looking off-camera or down at 15-20 degree angle for editorial mood",
    realismNotes:
      "Jacket opening is medium-difficulty for Higgsfield. Watch for: lapel shape consistency, lining rendering, hand gripping fabric naturally. Multiple layers can confuse garment boundaries.",
    whyItWorks:
      "Showing the jacket open communicates styling versatility and construction quality, making the product feel more premium and giving buyers a sense of how it wears in real life.",
    deltaBlueprint:
      "Tighten framing to three-quarter body. Model opens jacket with one hand on lapel, revealing the layer underneath. Angle camera 10-20 degrees to show depth inside the jacket. Soften aperture to f/4 for shallow focus on the opening. Editorial gaze, not direct to camera.",
  },

  // ────────────────────────────────────────────
  // 5. tailoring_lapel_touch
  // ────────────────────────────────────────────
  {
    id: "tailoring_lapel_touch",
    title: "Tailoring Lapel Touch",
    role: "Hand touching lapel to draw attention to construction and tailoring detail.",
    shotCategory: "product_focus",
    suitableFamilies: ["apparel"],
    suitableItems: ["blazer", "suit", "jacket", "sport coat", "tuxedo"],
    suitableGoals: ["premium_branding", "detail_focus"],
    suitableStyles: ["luxury", "tailoring", "commercial", "editorial"],
    suitableGenderPresentation: ["menswear", "womenswear", "unisex"],
    creativityBand: ["balanced"],
    logoVisibilitySuitability: "medium",
    productClaritySuitability: "medium",
    silhouetteSuitability: "low",
    detailSuitability: "high",
    movementSuitability: "low",
    editorialStrength: "medium",
    higgsfieldReliability: "medium",
    difficulty: "moderate",
    logoRisk: "medium",
    anatomyRisk: "medium",
    occlusionRisk: "medium",
    bestUsedWhen:
      "The lapel or collar construction is a selling point: peak lapels, notch lapels, contrast stitching, or branded hardware.",
    avoidWhen:
      "The garment has no lapel or collar detail, or when hand rendering near the face is too risky for the generation budget.",
    defaultFraming: "Half body, chest up, centred on upper torso and lapel area",
    defaultLens: "85mm",
    defaultAperture: "f/4",
    defaultCameraHeight: "eye level",
    defaultCameraDistance: "~2m",
    defaultAngle: "Straight on or very slight angle to show lapel dimension",
    defaultLighting: "Directional key light from camera-right to highlight lapel texture and stitching",
    poseFamily: "Standing detail-focused",
    bodyDirection: "Square to camera, very slight turn to give the lapel dimension",
    handBehavior: "One hand lightly touching or adjusting the lapel, fingers naturally curved",
    legBehavior: "Not visible in frame; stable standing stance assumed",
    headDirection: "Chin slightly down, gaze at camera or toward the hand for editorial feel",
    realismNotes:
      "Hand-near-face shots require careful hand rendering. Watch for: finger count, thumb placement, natural curvature of fingers on fabric. Lapel should not distort under hand pressure. May need 2-3 generations.",
    whyItWorks:
      "The lapel touch is a classic tailoring gesture that immediately signals craftsmanship, directing the buyer's eye to construction quality.",
    deltaBlueprint:
      "Crop to half body, chest and above. Move camera to eye level at ~2m. Model places one hand on lapel with fingers naturally curved. Slight chin-down angle. Open aperture to f/4 for shallow focus on the lapel zone. Lighting emphasises fabric texture and stitching detail.",
  },

  // ────────────────────────────────────────────
  // 6. cuff_adjustment_tailoring
  // ────────────────────────────────────────────
  {
    id: "cuff_adjustment_tailoring",
    title: "Cuff Adjustment Tailoring",
    role: "Close crop on cuff or sleeve adjustment, emphasising construction detail.",
    shotCategory: "detail",
    suitableFamilies: ["apparel"],
    suitableItems: ["shirt", "blazer", "suit", "jacket", "dress shirt", "sport coat"],
    suitableGoals: ["detail_focus", "premium_branding"],
    suitableStyles: ["luxury", "tailoring", "commercial", "minimal"],
    suitableGenderPresentation: ["menswear", "womenswear", "unisex"],
    creativityBand: ["safe", "balanced"],
    logoVisibilitySuitability: "medium",
    productClaritySuitability: "medium",
    silhouetteSuitability: "low",
    detailSuitability: "high",
    movementSuitability: "low",
    editorialStrength: "low",
    higgsfieldReliability: "medium",
    difficulty: "moderate",
    logoRisk: "low",
    anatomyRisk: "high",
    occlusionRisk: "low",
    bestUsedWhen:
      "The cuff, button, or sleeve detail is a design feature: French cuffs, contrast buttonholes, branded cufflinks, or rolled sleeves.",
    avoidWhen:
      "Plain, featureless sleeves with nothing to highlight, or when the generation budget is tight and hand rendering risk is unacceptable.",
    defaultFraming: "Tight crop on wrist/cuff area, forearm to fingertips",
    defaultLens: "85mm",
    defaultAperture: "f/2.8",
    defaultCameraHeight: "waist height",
    defaultCameraDistance: "~1.5m",
    defaultAngle: "Straight on or slightly above, looking down at the wrist",
    defaultLighting: "Focused key light on the cuff area, soft fill to preserve button and fabric detail",
    poseFamily: "Detail interaction",
    bodyDirection: "Not fully visible; forearm and hand are the subject",
    handBehavior: "One hand adjusting the opposite cuff, fingers visible and naturally positioned",
    legBehavior: "Not visible in frame",
    headDirection: "Not visible or cropped above chin; gaze implied downward",
    realismNotes:
      "High anatomy risk due to close-up hand rendering. Watch for: finger count on both hands, natural wrist angle, cuff button alignment. Fabric should not look melted or fused to skin. Expect to need 2-4 generations for clean hands.",
    whyItWorks:
      "The cuff adjustment is a universal gesture of refinement that communicates attention to detail and elevates perceived garment quality.",
    deltaBlueprint:
      "Tight crop: wrist and cuff only. Drop camera to waist height, close distance to ~1.5m. Open aperture to f/2.8 for shallow depth isolating the cuff. One hand adjusts opposite cuff. Focused directional light on the detail area. Everything outside the cuff zone falls away.",
  },

  // ────────────────────────────────────────────
  // 7. torso_turn_editorial
  // ────────────────────────────────────────────
  {
    id: "torso_turn_editorial",
    title: "Torso Turn Editorial",
    role: "Upper body rotation creating editorial depth and dynamic fabric movement.",
    shotCategory: "editorial",
    suitableFamilies: [
      "apparel",
      "footwear",
      "bags",
      "jewelry",
      "eyewear",
      "watches",
      "headwear",
      "belts",
      "scarves",
      "small_accessories",
      "full_look",
    ],
    suitableItems: [],
    suitableGoals: ["mood", "styling_story"],
    suitableStyles: ["editorial", "luxury", "contemporary", "avant_garde", "street"],
    suitableGenderPresentation: ["menswear", "womenswear", "unisex"],
    creativityBand: ["balanced", "directional"],
    logoVisibilitySuitability: "low",
    productClaritySuitability: "medium",
    silhouetteSuitability: "medium",
    detailSuitability: "low",
    movementSuitability: "medium",
    editorialStrength: "high",
    higgsfieldReliability: "medium",
    difficulty: "moderate",
    logoRisk: "high",
    anatomyRisk: "medium",
    occlusionRisk: "medium",
    bestUsedWhen:
      "The set needs editorial tension and you want to show fabric movement, drape, or texture from a dynamic angle.",
    avoidWhen:
      "Logo visibility is the primary goal, or the product is a small accessory that would be lost in the rotation.",
    defaultFraming: "Three-quarter body, waist up, allowing torso rotation to fill the frame",
    defaultLens: "85mm",
    defaultAperture: "f/4",
    defaultCameraHeight: "chest height",
    defaultCameraDistance: "~2.5m",
    defaultAngle: "15-30 degrees off-centre, following the direction of the torso turn",
    defaultLighting: "Directional key with harder falloff to accentuate fabric folds and shadow in the turn",
    poseFamily: "Torso rotation",
    bodyDirection: "Upper body twisted 20-40 degrees from hips, creating diagonal tension",
    handBehavior: "Arms follow the rotation naturally, one slightly forward, one trailing",
    legBehavior: "Hips remain relatively stable, slight weight shift to support the twist",
    headDirection: "Turned further than shoulders, looking over the leading shoulder or off-camera",
    realismNotes:
      "Torso rotation is moderately reliable but can distort waistline or create unnatural fabric bunching. Watch for: belt or waistband alignment, arm proportions in the twist, collar staying consistent.",
    whyItWorks:
      "The torso turn introduces controlled dynamism that breaks the static look of standard product photography, making the set feel editorially cohesive.",
    deltaBlueprint:
      "Reframe to three-quarter body. Model twists upper body 20-40 degrees from hips, head turned further over the leading shoulder. Camera follows rotation at 15-30 degrees off-centre. Increase lighting contrast to define fabric folds in the twist. Arms follow naturally, no rigid posing.",
  },

  // ────────────────────────────────────────────
  // 8. relaxed_lean
  // ────────────────────────────────────────────
  {
    id: "relaxed_lean",
    title: "Relaxed Lean",
    role: "Model leaning against a surface, conveying casual editorial energy and garment drape.",
    shotCategory: "editorial",
    suitableFamilies: ["apparel", "full_look"],
    suitableItems: [],
    suitableGoals: ["mood", "styling_story"],
    suitableStyles: ["editorial", "street", "contemporary", "resort", "luxury"],
    suitableGenderPresentation: ["menswear", "womenswear", "unisex"],
    creativityBand: ["balanced", "directional"],
    logoVisibilitySuitability: "low",
    productClaritySuitability: "medium",
    silhouetteSuitability: "medium",
    detailSuitability: "low",
    movementSuitability: "low",
    editorialStrength: "high",
    higgsfieldReliability: "medium",
    difficulty: "moderate",
    logoRisk: "high",
    anatomyRisk: "medium",
    occlusionRisk: "medium",
    bestUsedWhen:
      "You want to break the standing-pose monotony and convey effortless style, especially for casual or streetwear collections.",
    avoidWhen:
      "High logo visibility is required (lean can obscure front branding), or the background environment does not support a leaning surface.",
    defaultFraming: "Full body or three-quarter, showing the model's relationship to the surface",
    defaultLens: "85mm",
    defaultAperture: "f/4",
    defaultCameraHeight: "chest height",
    defaultCameraDistance: "~3.5m",
    defaultAngle: "10-25 degrees to the side, capturing the lean angle",
    defaultLighting: "Natural-feel directional light, slightly warmer tone for casual atmosphere",
    poseFamily: "Leaning editorial",
    bodyDirection: "Shoulder and back resting against wall or surface, body angled toward camera",
    handBehavior: "One hand in pocket or resting on thigh, other relaxed at side or holding accessory",
    legBehavior: "One leg straight supporting weight, other crossed in front or bent with foot against wall",
    headDirection: "Looking off-camera or down, 15-30 degree away from lens",
    realismNotes:
      "Leaning poses require a visible supporting surface. Watch for: model appearing to float if the wall or surface is not rendered, shoulder distortion at the contact point, garment bunching at the lean.",
    whyItWorks:
      "The lean communicates effortless confidence and makes the garment look lived-in rather than displayed, which resonates with editorial and lifestyle audiences.",
    deltaBlueprint:
      "Add a wall or architectural surface. Model leans back against it, one foot up against the surface. Shift gaze off-camera. Open framing to include the lean context. One hand in pocket for casual energy. Slightly warmer, natural lighting. Camera catches the relaxed angle from 10-25 degrees to the side.",
  },

  // ────────────────────────────────────────────
  // 9. side_silhouette
  // ────────────────────────────────────────────
  {
    id: "side_silhouette",
    title: "Side Silhouette",
    role: "Full profile view showing the clean garment line from the side.",
    shotCategory: "silhouette",
    suitableFamilies: ["apparel", "full_look"],
    suitableItems: [],
    suitableGoals: ["silhouette"],
    suitableStyles: [
      "commercial",
      "editorial",
      "luxury",
      "minimal",
      "tailoring",
      "contemporary",
      "avant_garde",
    ],
    suitableGenderPresentation: ["menswear", "womenswear", "unisex"],
    creativityBand: ["safe", "balanced", "directional"],
    logoVisibilitySuitability: "low",
    productClaritySuitability: "medium",
    silhouetteSuitability: "high",
    detailSuitability: "low",
    movementSuitability: "low",
    editorialStrength: "medium",
    higgsfieldReliability: "high",
    difficulty: "easy",
    logoRisk: "high",
    anatomyRisk: "low",
    occlusionRisk: "low",
    bestUsedWhen:
      "The garment has a strong profile, such as structured shoulders, exaggerated proportions, or a distinctive hemline.",
    avoidWhen:
      "Front branding is critical, or the garment reads identically from the side as it does from the front.",
    defaultFraming: "Full body, head to toe, maximum negative space in front and behind",
    defaultLens: "85mm",
    defaultAperture: "f/5.6",
    defaultCameraHeight: "chest height",
    defaultCameraDistance: "~4m",
    defaultAngle: "90 degrees, camera directly at model's side (true profile)",
    defaultLighting: "Backlight for strong edge definition, soft frontal fill to preserve some detail",
    poseFamily: "Standing profile",
    bodyDirection: "Full side-on, perpendicular to camera",
    handBehavior: "Hands at sides or one slightly forward for natural arm swing",
    legBehavior: "Feet together or one slightly forward for a subtle stride suggestion",
    headDirection: "Profile view, chin parallel to floor or very slightly lifted",
    realismNotes:
      "True profile is reliable for Higgsfield. Watch for: nose and chin rendering in profile, ear visibility, far-side arm creating awkward shapes behind the torso. Keep hands simple.",
    whyItWorks:
      "A true side profile isolates the garment's silhouette in a way no other angle can, making it the definitive shape reference for the lookbook.",
    deltaBlueprint:
      "Rotate camera to 90 degrees for true profile. Model stands side-on, chin parallel to floor. Add backlight for strong edge separation. Maximise negative space on both sides. Hands stay at sides to preserve the unbroken silhouette line. No body rotation.",
  },

  // ────────────────────────────────────────────
  // 10. back_view_shape
  // ────────────────────────────────────────────
  {
    id: "back_view_shape",
    title: "Back View Shape",
    role: "Rear view showing back construction, shape, and detail.",
    shotCategory: "silhouette",
    suitableFamilies: ["apparel"],
    suitableItems: [],
    suitableGoals: ["silhouette", "detail_focus"],
    suitableStyles: ["editorial", "luxury", "tailoring", "commercial", "minimal", "contemporary"],
    suitableGenderPresentation: ["menswear", "womenswear", "unisex"],
    creativityBand: ["balanced", "directional"],
    logoVisibilitySuitability: "low",
    productClaritySuitability: "medium",
    silhouetteSuitability: "high",
    detailSuitability: "medium",
    movementSuitability: "low",
    editorialStrength: "medium",
    higgsfieldReliability: "high",
    difficulty: "easy",
    logoRisk: "high",
    anatomyRisk: "low",
    occlusionRisk: "low",
    bestUsedWhen:
      "The garment has back-specific design features: back vents, pleats, yoke seams, interesting stitching, or a distinctive back silhouette.",
    avoidWhen:
      "Logo or front branding visibility is the primary goal. Avoid if the back is plain and undifferentiated.",
    defaultFraming: "Full body from behind, head to toe, centred",
    defaultLens: "85mm",
    defaultAperture: "f/5.6",
    defaultCameraHeight: "chest height",
    defaultCameraDistance: "~4m",
    defaultAngle: "Directly behind model (180 degrees from front), or 160-170 degrees for slight reveal",
    defaultLighting: "Soft key from camera-right (model's left from behind), edge light for shoulder definition",
    poseFamily: "Standing rear view",
    bodyDirection: "Back facing camera, square or with very slight hip offset",
    handBehavior: "Relaxed at sides, not tucked behind the body",
    legBehavior: "Natural stance, feet shoulder-width or slightly staggered",
    headDirection: "Looking straight ahead (away from camera) or turned 15-20 degrees over shoulder for editorial edge",
    realismNotes:
      "Rear views are highly reliable for Higgsfield. Minimal face rendering reduces artifact risk. Watch for: hair covering back details, belt or waistband alignment, back vent rendering on blazers.",
    whyItWorks:
      "The back view completes the 360-degree product story, showing construction details and proportions that buyers cannot see from front or side angles.",
    deltaBlueprint:
      "Move camera behind the model. Full body framing from the rear. Model stands naturally with slight hip offset. Head turned 15-20 degrees over shoulder for subtle editorial quality. Lighting defines shoulder line and back construction. Hands relaxed at sides, not tucked.",
  },

  // ────────────────────────────────────────────
  // 11. controlled_half_stride
  // ────────────────────────────────────────────
  {
    id: "controlled_half_stride",
    title: "Controlled Half Stride",
    role: "Subtle walking motion with one foot forward, capturing garment movement.",
    shotCategory: "motion",
    suitableFamilies: ["apparel", "footwear", "full_look"],
    suitableItems: [],
    suitableGoals: ["movement", "mood"],
    suitableStyles: ["editorial", "street", "contemporary", "resort", "commercial"],
    suitableGenderPresentation: ["menswear", "womenswear", "unisex"],
    creativityBand: ["balanced", "directional"],
    logoVisibilitySuitability: "medium",
    productClaritySuitability: "medium",
    silhouetteSuitability: "medium",
    detailSuitability: "low",
    movementSuitability: "high",
    editorialStrength: "medium",
    higgsfieldReliability: "medium",
    difficulty: "moderate",
    logoRisk: "medium",
    anatomyRisk: "medium",
    occlusionRisk: "low",
    bestUsedWhen:
      "The set needs motion energy, or the garment has movement properties worth showing: flowy fabrics, trench coats, wide-leg trousers, or sneakers.",
    avoidWhen:
      "Safe creativity is required and there is no budget for re-generation, or the garment is rigid and does not benefit from motion.",
    defaultFraming: "Full body, head to toe, with extra space in the direction of movement",
    defaultLens: "85mm",
    defaultAperture: "f/5.6",
    defaultCameraHeight: "waist height",
    defaultCameraDistance: "~4m",
    defaultAngle: "Slight angle from the direction of movement, 10-20 degrees",
    defaultLighting: "Directional natural light, allowing subtle shadow movement",
    poseFamily: "Walking mid-stride",
    bodyDirection: "Moving toward or across camera, body angled 10-20 degrees off straight-on",
    handBehavior: "Natural arm swing, opposite arm forward to the leading leg",
    legBehavior: "One leg forward mid-stride, rear leg pushing off, slight bend in both knees",
    headDirection: "Looking in direction of movement or angled toward camera",
    realismNotes:
      "Mid-stride is moderately reliable but introduces foot rendering risk. Watch for: foot contact with ground, natural knee bend, fabric flow direction matching movement, arm swing symmetry. Avoid extreme stride length.",
    whyItWorks:
      "A controlled stride shows how the garment behaves in motion, adding energy and realism that static poses cannot achieve.",
    deltaBlueprint:
      "Model mid-stride with one foot forward, natural arm swing. Drop camera to waist height for slight low-angle energy. Add negative space in the walking direction. Keep stride small and controlled; this is a walk, not a run. Fabric should show subtle movement. Slight angle off straight-on.",
  },

  // ────────────────────────────────────────────
  // 12. pivot_step
  // ────────────────────────────────────────────
  {
    id: "pivot_step",
    title: "Pivot Step",
    role: "Caught mid-pivot, rotational energy and fabric twist.",
    shotCategory: "motion",
    suitableFamilies: ["apparel", "full_look"],
    suitableItems: [],
    suitableGoals: ["movement", "mood"],
    suitableStyles: ["editorial", "avant_garde", "contemporary", "street"],
    suitableGenderPresentation: ["menswear", "womenswear", "unisex"],
    creativityBand: ["directional"],
    logoVisibilitySuitability: "low",
    productClaritySuitability: "low",
    silhouetteSuitability: "medium",
    detailSuitability: "low",
    movementSuitability: "high",
    editorialStrength: "high",
    higgsfieldReliability: "medium",
    difficulty: "moderate",
    logoRisk: "high",
    anatomyRisk: "medium",
    occlusionRisk: "medium",
    bestUsedWhen:
      "The set needs a dramatic motion shot and the garment has rotational drape: coats, skirts, wide trousers, flowing dresses.",
    avoidWhen:
      "Logo visibility matters, the garment is rigid (structured blazer with no drape), or the creativity level is safe.",
    defaultFraming: "Full body, head to toe, generous framing to capture the arc of rotation",
    defaultLens: "85mm",
    defaultAperture: "f/4",
    defaultCameraHeight: "waist height",
    defaultCameraDistance: "~4m",
    defaultAngle: "20-30 degrees off the pivot direction to catch the spiral",
    defaultLighting: "Dynamic directional light, slightly harder edge to define motion blur and fabric arc",
    poseFamily: "Pivot rotation",
    bodyDirection: "Mid-rotation, torso and legs at different angles, fabric trailing the turn",
    handBehavior: "Arms flowing outward with the rotation, relaxed and trailing",
    legBehavior: "One foot planted as pivot point, other stepping around, body weight transitioning",
    headDirection: "Leading the rotation, chin up, looking in the direction of the pivot",
    realismNotes:
      "Pivot shots have moderate reliability. Watch for: foot placement on ground, fabric direction consistency (all fabric should trail in the same rotational direction), arm positions matching rotational momentum. Expect 3-5 generations to get a clean result.",
    whyItWorks:
      "The pivot is the highest-energy motion shot, showing how fabric responds to rotational force and creating the most visually dramatic frame in the set.",
    deltaBlueprint:
      "Model caught mid-pivot, one foot planted. Body and fabric trail the rotation. Camera offset 20-30 degrees to catch the spiral. Drop to waist height, open to f/4. Arms flow outward. Generous framing to contain the full arc of movement. This is the most directional shot in the set.",
  },

  // ────────────────────────────────────────────
  // 13. seated_edge_pose
  // ────────────────────────────────────────────
  {
    id: "seated_edge_pose",
    title: "Seated Edge Pose",
    role: "Model seated on the edge of a surface, showing garment drape and casual editorial energy.",
    shotCategory: "editorial",
    suitableFamilies: ["apparel", "full_look"],
    suitableItems: [],
    suitableGoals: ["mood", "styling_story"],
    suitableStyles: ["editorial", "luxury", "contemporary", "resort", "minimal"],
    suitableGenderPresentation: ["menswear", "womenswear", "unisex"],
    creativityBand: ["balanced", "directional"],
    logoVisibilitySuitability: "medium",
    productClaritySuitability: "medium",
    silhouetteSuitability: "low",
    detailSuitability: "low",
    movementSuitability: "low",
    editorialStrength: "high",
    higgsfieldReliability: "medium",
    difficulty: "moderate",
    logoRisk: "medium",
    anatomyRisk: "medium",
    occlusionRisk: "medium",
    bestUsedWhen:
      "The set needs variety from standing poses and the garment has interesting drape when seated: trousers pooling, jacket falling open, knitwear relaxing.",
    avoidWhen:
      "Full garment visibility is critical (seated crops lower body), or the environment does not support a seating surface.",
    defaultFraming: "Three-quarter to full body, capturing the seated posture and garment fall",
    defaultLens: "85mm",
    defaultAperture: "f/4",
    defaultCameraHeight: "eye level (seated eye level)",
    defaultCameraDistance: "~3m",
    defaultAngle: "10-20 degrees off straight-on, slight three-quarter",
    defaultLighting: "Soft directional key, warm fill for relaxed mood",
    poseFamily: "Seated casual",
    bodyDirection: "Seated on edge of surface, torso upright or slightly leaned back",
    handBehavior: "One hand resting on knee or surface, other relaxed at side or on thigh",
    legBehavior: "One leg extended or crossed, other foot on floor, showing trouser drape",
    headDirection: "Looking off-camera or slight down angle for editorial contemplation",
    realismNotes:
      "Seated poses require a visible surface. Watch for: model floating above seat, trouser crease patterns at the hip, hand placement on knee looking natural. Seated body proportions can compress the torso.",
    whyItWorks:
      "Seated poses break the standing-pose rhythm and show how the garment behaves in a relaxed state, communicating versatility and effortless style.",
    deltaBlueprint:
      "Add a low surface (bench, step, ledge). Model sits on edge, one leg extended. Torso upright, one hand on knee. Camera at seated eye level, ~3m back. Gaze off-camera for editorial mood. Show how fabric drapes and pools when seated. Warm fill light for relaxed atmosphere.",
  },

  // ────────────────────────────────────────────
  // 14. seated_forward_lean
  // ────────────────────────────────────────────
  {
    id: "seated_forward_lean",
    title: "Seated Forward Lean",
    role: "Forward lean from seated position, elbows on knees, intimate editorial mood.",
    shotCategory: "editorial",
    suitableFamilies: ["apparel", "full_look"],
    suitableItems: [],
    suitableGoals: ["mood"],
    suitableStyles: ["editorial", "contemporary", "avant_garde", "street"],
    suitableGenderPresentation: ["menswear", "womenswear", "unisex"],
    creativityBand: ["directional"],
    logoVisibilitySuitability: "low",
    productClaritySuitability: "low",
    silhouetteSuitability: "low",
    detailSuitability: "low",
    movementSuitability: "low",
    editorialStrength: "high",
    higgsfieldReliability: "medium",
    difficulty: "moderate",
    logoRisk: "high",
    anatomyRisk: "medium",
    occlusionRisk: "high",
    bestUsedWhen:
      "The set needs a moody, intimate editorial moment, and the garment benefits from a compressed, relaxed posture, such as knitwear or casual tailoring.",
    avoidWhen:
      "Product clarity is the primary goal, logo visibility is critical, or the creativity level is safe or balanced.",
    defaultFraming: "Three-quarter body, seated, emphasis on upper body and forward lean",
    defaultLens: "85mm",
    defaultAperture: "f/2.8",
    defaultCameraHeight: "Slightly below seated eye level for intimacy",
    defaultCameraDistance: "~2.5m",
    defaultAngle: "Straight on or very slight angle, 5-10 degrees",
    defaultLighting: "Moody directional key, deeper shadows, minimal fill for dramatic contrast",
    poseFamily: "Seated forward lean",
    bodyDirection: "Torso leaned forward over knees, back curved, shoulders rounded",
    handBehavior: "Elbows on knees, hands clasped or hanging loosely between legs",
    legBehavior: "Feet planted, knees apart, supporting the forward lean",
    headDirection: "Looking directly at camera through lowered brow, or gaze dropped to hands",
    realismNotes:
      "Forward lean compresses the torso and creates complex fabric folds. Watch for: jacket bunching at the waist, hand rendering between the knees, face being too close to hands creating merging artifacts. Keep the pose degree moderate.",
    whyItWorks:
      "The forward lean creates psychological intimacy and editorial gravitas, making the viewer feel drawn into the image rather than observing from a distance.",
    deltaBlueprint:
      "Seated setup with model leaning forward, elbows on knees. Drop camera slightly below seated eye level. Open aperture to f/2.8 for shallow depth. Deepen shadows with minimal fill. Hands clasped or loose between legs. This is a mood-first shot; product visibility is secondary to editorial atmosphere.",
  },

  // ────────────────────────────────────────────
  // 15. detail_crop_logo_focus
  // ────────────────────────────────────────────
  {
    id: "detail_crop_logo_focus",
    title: "Detail Crop Logo Focus",
    role: "Tight crop on the logo, branding, or label area for maximum brand visibility.",
    shotCategory: "detail",
    suitableFamilies: [
      "apparel",
      "footwear",
      "bags",
      "jewelry",
      "eyewear",
      "watches",
      "headwear",
      "belts",
      "scarves",
      "small_accessories",
      "full_look",
    ],
    suitableItems: [],
    suitableGoals: ["premium_branding", "detail_focus", "product_clarity"],
    suitableStyles: [
      "commercial",
      "luxury",
      "minimal",
      "tailoring",
      "editorial",
      "contemporary",
    ],
    suitableGenderPresentation: ["menswear", "womenswear", "unisex"],
    creativityBand: ["safe", "balanced"],
    logoVisibilitySuitability: "high",
    productClaritySuitability: "high",
    silhouetteSuitability: "low",
    detailSuitability: "high",
    movementSuitability: "low",
    editorialStrength: "low",
    higgsfieldReliability: "high",
    difficulty: "easy",
    logoRisk: "low",
    anatomyRisk: "low",
    occlusionRisk: "low",
    bestUsedWhen:
      "The product has visible branding, a prominent logo, branded hardware, or label detail that is a selling point.",
    avoidWhen: "The product has no visible branding or the logo is unrecognisable at crop scale.",
    defaultFraming: "Extreme close-up on the logo or branding zone, filling 60-80% of the frame",
    defaultLens: "85mm",
    defaultAperture: "f/2.8",
    defaultCameraHeight: "Aligned with the logo position on the body",
    defaultCameraDistance: "~1.5m",
    defaultAngle: "Perpendicular to the branding surface for maximum legibility",
    defaultLighting: "Even, soft directional light to ensure logo legibility without glare",
    poseFamily: "Static detail",
    bodyDirection: "Whatever angle presents the logo flat to camera",
    handBehavior: "Not in frame, or one hand subtly framing the logo area without covering it",
    legBehavior: "Not visible in frame",
    headDirection: "Not visible in frame",
    realismNotes:
      "Logo and text rendering is Higgsfield's weakest area. Watch for: letter distortion, mirrored text, blurred logo edges, characters merging. Use only when the brand name is short or iconic. Expect 2-3 generations for legibility.",
    whyItWorks:
      "A dedicated logo crop validates the product's brand authenticity and gives buyers the close-up brand assurance that wide shots cannot provide.",
    deltaBlueprint:
      "Extreme close-up: crop to the logo or branding zone only. Camera perpendicular to the branding surface. Open aperture to f/2.8 for shallow focus isolating the logo. Even, glare-free lighting. No hands, no face. The brand mark fills the frame. This is a branding validation shot.",
  },

  // ────────────────────────────────────────────
  // 16. accessory_hand_interaction
  // ────────────────────────────────────────────
  {
    id: "accessory_hand_interaction",
    title: "Accessory Hand Interaction",
    role: "Hand interacting with a small accessory, drawing attention to its design and scale.",
    shotCategory: "product_focus",
    suitableFamilies: ["jewelry", "watches", "small_accessories"],
    suitableItems: ["ring", "bracelet", "watch", "cufflink", "tie pin", "pocket square", "keychain"],
    suitableGoals: ["detail_focus", "product_clarity"],
    suitableStyles: ["luxury", "commercial", "minimal", "editorial", "tailoring"],
    suitableGenderPresentation: ["menswear", "womenswear", "unisex"],
    creativityBand: ["safe", "balanced"],
    logoVisibilitySuitability: "high",
    productClaritySuitability: "high",
    silhouetteSuitability: "low",
    detailSuitability: "high",
    movementSuitability: "low",
    editorialStrength: "medium",
    higgsfieldReliability: "medium",
    difficulty: "moderate",
    logoRisk: "low",
    anatomyRisk: "high",
    occlusionRisk: "low",
    bestUsedWhen:
      "The hero product is a small accessory that needs hand context for scale and styling, such as rings, bracelets, watches, or cufflinks.",
    avoidWhen:
      "The product is large (bags, apparel) where hand interaction is less relevant, or the hand rendering budget is exhausted.",
    defaultFraming: "Tight crop on hand and accessory, filling 70% of frame",
    defaultLens: "85mm",
    defaultAperture: "f/2.8",
    defaultCameraHeight: "Aligned with the accessory position",
    defaultCameraDistance: "~1.5m",
    defaultAngle: "Slight overhead or perpendicular to the accessory face",
    defaultLighting: "Focused spot or directional key to catch metal and gemstone reflections",
    poseFamily: "Hand detail interaction",
    bodyDirection: "Not visible or minimally visible; hand and accessory are the subject",
    handBehavior: "One hand presenting or adjusting the accessory, fingers elegantly positioned",
    legBehavior: "Not visible in frame",
    headDirection: "Not visible in frame",
    realismNotes:
      "High anatomy risk due to close-up hand rendering with small objects. Watch for: finger count, ring or bracelet floating above skin, watch face legibility, natural finger curvature. Metal reflections can look artificial. Expect 3-5 generations.",
    whyItWorks:
      "Hand interaction provides scale context and styling inspiration for small accessories, making the product feel wearable rather than isolated on a flat surface.",
    deltaBlueprint:
      "Tight crop on the hand and accessory. Camera at accessory height, ~1.5m. Open to f/2.8 for shallow depth isolating the piece. Focused directional light to catch metallic or textured surfaces. One hand presents or adjusts the accessory with fingers naturally curved. Background falls away completely.",
  },

  // ────────────────────────────────────────────
  // 17. eyewear_portrait_halfbody
  // ────────────────────────────────────────────
  {
    id: "eyewear_portrait_halfbody",
    title: "Eyewear Portrait Half-Body",
    role: "Half-body portrait optimised for eyewear product visibility and face framing.",
    shotCategory: "product_focus",
    suitableFamilies: ["eyewear"],
    suitableItems: ["sunglasses", "glasses", "optical frames", "aviators", "wayfarers"],
    suitableGoals: ["product_clarity", "premium_branding", "detail_focus"],
    suitableStyles: ["luxury", "commercial", "editorial", "contemporary", "minimal"],
    suitableGenderPresentation: ["menswear", "womenswear", "unisex"],
    creativityBand: ["safe", "balanced"],
    logoVisibilitySuitability: "high",
    productClaritySuitability: "high",
    silhouetteSuitability: "low",
    detailSuitability: "high",
    movementSuitability: "low",
    editorialStrength: "medium",
    higgsfieldReliability: "medium",
    difficulty: "moderate",
    logoRisk: "low",
    anatomyRisk: "medium",
    occlusionRisk: "low",
    bestUsedWhen:
      "The hero product is eyewear and needs to be shown on a face for fit, scale, and styling context.",
    avoidWhen:
      "The eyewear is not the hero product and is just part of a styling set. Use hero_full_body_seller instead.",
    defaultFraming: "Half body, chest up, face and eyewear as the focal area",
    defaultLens: "85mm",
    defaultAperture: "f/2.8",
    defaultCameraHeight: "eye level",
    defaultCameraDistance: "~2m",
    defaultAngle: "Straight on or very slight three-quarter (5-10 degrees) for frame dimension",
    defaultLighting: "Soft beauty light from above, gentle fill to prevent lens glare, catchlight in lenses",
    poseFamily: "Portrait static",
    bodyDirection: "Square to camera, shoulders relaxed, slight forward energy",
    handBehavior: "Not touching face; one hand may rest at side or adjust collar below frame",
    legBehavior: "Not visible in frame",
    headDirection: "Straight to camera for symmetry, or 10-degree turn to show frame thickness",
    realismNotes:
      "Eyewear rendering is moderately reliable. Watch for: frame symmetry on the face, lens reflection consistency, temple arm alignment with ears, nose bridge fit. Avoid direct lighting that creates harsh reflections in lenses.",
    whyItWorks:
      "A half-body portrait lets buyers see how the eyewear frames the face, which is the primary purchase decision factor for eyewear products.",
    deltaBlueprint:
      "Crop to half body, face and chest. Camera at eye level, ~2m, straight on. Open to f/2.8 for shallow depth on the frames. Soft overhead beauty light with controlled fill to prevent lens glare. Model faces camera directly, hands away from face. The eyewear is the hero, not the outfit.",
  },

  // ────────────────────────────────────────────
  // 18. jewelry_neckline_focus
  // ────────────────────────────────────────────
  {
    id: "jewelry_neckline_focus",
    title: "Jewelry Neckline Focus",
    role: "Close crop on neckline or ear area to showcase jewelry placement and detail.",
    shotCategory: "detail",
    suitableFamilies: ["jewelry"],
    suitableItems: ["necklace", "pendant", "choker", "earring", "ear cuff", "chain"],
    suitableGoals: ["detail_focus", "product_clarity"],
    suitableStyles: ["luxury", "commercial", "editorial", "minimal", "contemporary"],
    suitableGenderPresentation: ["menswear", "womenswear", "unisex"],
    creativityBand: ["safe", "balanced"],
    logoVisibilitySuitability: "high",
    productClaritySuitability: "high",
    silhouetteSuitability: "low",
    detailSuitability: "high",
    movementSuitability: "low",
    editorialStrength: "medium",
    higgsfieldReliability: "medium",
    difficulty: "moderate",
    logoRisk: "low",
    anatomyRisk: "medium",
    occlusionRisk: "low",
    bestUsedWhen:
      "The hero product is a necklace, pendant, earring, or any jewelry worn near the neckline or ear.",
    avoidWhen:
      "The jewelry is a ring or bracelet (use accessory_hand_interaction instead), or the piece is too small to be visible at crop scale.",
    defaultFraming: "Close crop from chin to collarbone, or ear to shoulder for earrings",
    defaultLens: "85mm",
    defaultAperture: "f/2.8",
    defaultCameraHeight: "Eye level to slightly above",
    defaultCameraDistance: "~1.5m",
    defaultAngle: "Slight angle (10-15 degrees) to show pendant depth or earring dimension",
    defaultLighting: "Directional key from camera-right to catch metal reflections and gemstone sparkle",
    poseFamily: "Portrait detail",
    bodyDirection: "Chin slightly lifted to open the neckline area, or head turned for earring emphasis",
    handBehavior: "Not in frame; avoid touching the jewelry to prevent occlusion",
    legBehavior: "Not visible in frame",
    headDirection: "Chin up and slight turn for neckline, or profile for earring",
    realismNotes:
      "Jewelry rendering near skin is moderately difficult. Watch for: chain links merging, pendant floating above skin, earring clip not connecting to ear, metal colour consistency. Gemstone reflections may look flat.",
    whyItWorks:
      "A neckline or ear crop shows the jewelry in its wearing context at a scale where buyers can appreciate the craftsmanship, metal finish, and gemstone detail.",
    deltaBlueprint:
      "Crop to neckline area (chin to collarbone) or ear zone. Camera at eye level, ~1.5m, angled 10-15 degrees. Open to f/2.8 for shallow depth on the jewelry. Directional light to catch metal reflections. Chin lifted to expose the neckline. No hands near the jewelry. The piece sits against skin as the focal point.",
  },

  // ────────────────────────────────────────────
  // 19. bag_carry_profile
  // ────────────────────────────────────────────
  {
    id: "bag_carry_profile",
    title: "Bag Carry Profile",
    role: "Bag carried at side or shoulder from a profile angle, showing shape and carry style.",
    shotCategory: "product_focus",
    suitableFamilies: ["bags"],
    suitableItems: [
      "tote",
      "crossbody",
      "shoulder bag",
      "clutch",
      "backpack",
      "messenger",
      "handbag",
      "briefcase",
    ],
    suitableGoals: ["product_clarity", "silhouette"],
    suitableStyles: ["commercial", "luxury", "editorial", "street", "contemporary", "minimal"],
    suitableGenderPresentation: ["menswear", "womenswear", "unisex"],
    creativityBand: ["safe", "balanced"],
    logoVisibilitySuitability: "high",
    productClaritySuitability: "high",
    silhouetteSuitability: "high",
    detailSuitability: "medium",
    movementSuitability: "low",
    editorialStrength: "medium",
    higgsfieldReliability: "medium",
    difficulty: "moderate",
    logoRisk: "low",
    anatomyRisk: "medium",
    occlusionRisk: "medium",
    bestUsedWhen:
      "The hero product is a bag and needs to be shown in its carry position for scale, strap drop, and silhouette.",
    avoidWhen:
      "The bag is very small and would be lost in a profile full-body shot. Use accessory_hand_interaction for small clutches.",
    defaultFraming: "Three-quarter to full body, with the bag side facing camera",
    defaultLens: "85mm",
    defaultAperture: "f/4",
    defaultCameraHeight: "Aligned with the bag position (hip to shoulder depending on bag type)",
    defaultCameraDistance: "~3m",
    defaultAngle: "Profile or three-quarter angle (60-90 degrees) to show bag shape",
    defaultLighting: "Directional key to define bag shape and hardware, controlled highlights on leather or fabric",
    poseFamily: "Standing profile with bag",
    bodyDirection: "Profile or three-quarter, bag-side toward camera",
    handBehavior: "Hand holding bag strap or handle naturally; far hand relaxed",
    legBehavior: "Natural stance, slight weight shift toward the bag side",
    headDirection: "Looking straight ahead or slightly toward camera for connection",
    realismNotes:
      "Bag rendering is moderately reliable. Watch for: strap attachment points, hardware rendering (buckles, zippers), bag proportions against the body, handle deformation where hand grips. Crossbody straps can merge with clothing.",
    whyItWorks:
      "A profile carry shot shows the bag's real-world proportions against the body, strap drop length, and silhouette shape, which are the primary purchase considerations for bags.",
    deltaBlueprint:
      "Rotate camera to profile angle (60-90 degrees) with bag side facing lens. Model carries the bag naturally at the intended position. Camera height matches the bag. Open to f/4 with directional light defining bag shape and hardware. Three-quarter to full body framing, with the bag as the visual anchor.",
  },

  // ────────────────────────────────────────────
  // 20. footwear_ground_focus
  // ────────────────────────────────────────────
  {
    id: "footwear_ground_focus",
    title: "Footwear Ground Focus",
    role: "Low-angle emphasis on shoes, showing design, sole, and ground presence.",
    shotCategory: "product_focus",
    suitableFamilies: ["footwear"],
    suitableItems: [
      "sneakers",
      "loafers",
      "boots",
      "heels",
      "sandals",
      "dress shoes",
      "oxford",
      "derby",
      "mules",
    ],
    suitableGoals: ["product_clarity", "detail_focus"],
    suitableStyles: ["commercial", "luxury", "street", "editorial", "contemporary", "minimal"],
    suitableGenderPresentation: ["menswear", "womenswear", "unisex"],
    creativityBand: ["safe", "balanced"],
    logoVisibilitySuitability: "high",
    productClaritySuitability: "high",
    silhouetteSuitability: "medium",
    detailSuitability: "high",
    movementSuitability: "low",
    editorialStrength: "medium",
    higgsfieldReliability: "medium",
    difficulty: "moderate",
    logoRisk: "low",
    anatomyRisk: "medium",
    occlusionRisk: "low",
    bestUsedWhen:
      "The hero product is footwear and needs to be shown from below to emphasise design, sole detail, material texture, and ground presence.",
    avoidWhen:
      "Footwear is a secondary styling element rather than the hero, or the generation budget does not allow for low-angle experiments.",
    defaultFraming: "Cropped at knee or below, full shoe visibility, both feet in frame",
    defaultLens: "35mm",
    defaultAperture: "f/4",
    defaultCameraHeight: "ground level",
    defaultCameraDistance: "~2m",
    defaultAngle: "Low angle, 10-20 degrees above ground level, looking slightly up",
    defaultLighting: "Directional side light at ground level to define sole edges and material texture",
    poseFamily: "Standing footwear emphasis",
    bodyDirection: "Legs and feet are the subject; slight weight shift for asymmetry",
    handBehavior: "Not visible in frame",
    legBehavior: "One foot slightly forward or angled to show shoe profile, weight on rear foot",
    headDirection: "Not visible in frame or cropped above waist",
    realismNotes:
      "Low-angle footwear is moderately reliable. Watch for: sole-to-ground contact (shoes should not float), lace and strap rendering, material texture at close range. Ground surface texture matters for realism. Trouser-shoe junction is a risk area.",
    whyItWorks:
      "A low-angle footwear shot shows the shoe's design language, sole construction, and material quality from the perspective that best communicates its presence and craftsmanship.",
    deltaBlueprint:
      "Drop camera to ground level, 10-20 degrees up. Crop at knee, both shoes in frame. One foot forward to show profile. Use 35mm lens for slight wide-angle presence. Directional side light at ground level to define sole edges and material texture. Trouser hem visible but the shoe is the hero.",
  },

  // ────────────────────────────────────────────
  // 21. mood_environmental_hero
  // ────────────────────────────────────────────
  {
    id: "mood_environmental_hero",
    title: "Mood Environmental Hero",
    role: "Wide environmental shot with the model placed in a contextual setting for maximum editorial atmosphere.",
    shotCategory: "editorial",
    suitableFamilies: [
      "apparel",
      "footwear",
      "bags",
      "jewelry",
      "eyewear",
      "watches",
      "headwear",
      "belts",
      "scarves",
      "small_accessories",
      "full_look",
    ],
    suitableItems: [],
    suitableGoals: ["mood", "styling_story"],
    suitableStyles: ["editorial", "resort", "street", "contemporary", "avant_garde", "luxury"],
    suitableGenderPresentation: ["menswear", "womenswear", "unisex"],
    creativityBand: ["directional"],
    logoVisibilitySuitability: "low",
    productClaritySuitability: "low",
    silhouetteSuitability: "medium",
    detailSuitability: "low",
    movementSuitability: "medium",
    editorialStrength: "high",
    higgsfieldReliability: "medium",
    difficulty: "hard",
    logoRisk: "high",
    anatomyRisk: "medium",
    occlusionRisk: "medium",
    bestUsedWhen:
      "The set needs a closing or opening hero that sets the editorial mood, and the brand story benefits from environmental context, such as architecture, nature, or urban settings.",
    avoidWhen:
      "Product clarity or logo visibility is the primary goal, creativity level is safe, or the set is short (3 shots or fewer where every frame must sell product).",
    defaultFraming: "Wide shot, model occupying 30-40% of the frame, environment filling the rest",
    defaultLens: "35mm",
    defaultAperture: "f/5.6",
    defaultCameraHeight: "Eye level or slightly below for grandeur",
    defaultCameraDistance: "~6m",
    defaultAngle: "Straight on or slight angle depending on the environment composition",
    defaultLighting: "Natural environmental light, golden hour or overcast for mood, minimal artificial fill",
    poseFamily: "Environmental standing",
    bodyDirection: "Natural orientation within the space, facing camera or three-quarter toward camera",
    handBehavior: "Relaxed and natural; may interact with the environment (hand on railing, touching wall)",
    legBehavior: "Natural stance or subtle stride; planted and grounded in the environment",
    headDirection: "Looking at camera, off into distance, or toward a visual anchor in the environment",
    realismNotes:
      "Environmental shots are the hardest for Higgsfield due to complex background rendering. Watch for: background perspective inconsistency, model scale relative to environment, lighting direction matching between model and background, shadow direction consistency. Expect 3-6 generations.",
    whyItWorks:
      "An environmental hero places the product in a world, transforming the lookbook from a product catalogue into a brand story that buyers emotionally connect with.",
    deltaBlueprint:
      "Switch to 35mm lens, pull camera back to ~6m for a wide environmental frame. Model occupies 30-40% of the image, environment provides context and mood. Natural or golden-hour lighting. Relaxed pose within the space. This is the editorial bookend of the set; product detail is secondary to atmosphere and brand world.",
  },

  // ────────────────────────────────────────────
  // 22. portrait_hero_clean
  // ────────────────────────────────────────────
  {
    id: "portrait_hero_clean",
    title: "Portrait Hero Clean",
    role: "Primary product visibility for face/neck/ear-worn jewelry. Clean half-body portrait as anchor.",
    shotCategory: "hero",
    suitableFamilies: ["jewelry", "eyewear"],
    suitableItems: ["earrings", "earring", "ear cuff", "necklace", "pendant", "choker", "sunglasses", "glasses"],
    suitableGoals: ["product_clarity", "premium_branding", "detail_focus"],
    suitableStyles: ["commercial", "luxury", "editorial", "minimal", "contemporary"],
    suitableGenderPresentation: ["menswear", "womenswear", "unisex"],
    creativityBand: ["safe", "balanced"],
    logoVisibilitySuitability: "high",
    productClaritySuitability: "high",
    silhouetteSuitability: "low",
    detailSuitability: "high",
    movementSuitability: "low",
    editorialStrength: "medium",
    higgsfieldReliability: "high",
    difficulty: "easy",
    logoRisk: "low",
    anatomyRisk: "low",
    occlusionRisk: "low",
    bestUsedWhen:
      "The hero product is worn on the face, ear, or neckline. This replaces full-body hero for jewelry, earrings, and eyewear.",
    avoidWhen: "The product is apparel or a full outfit where body proportions matter.",
    defaultFraming: "Half body, shoulders up, face and product zone centred in frame",
    defaultLens: "85mm",
    defaultAperture: "f/4",
    defaultCameraHeight: "eye level",
    defaultCameraDistance: "~2m",
    defaultAngle: "Straight on or 5-degree turn for gentle dimension",
    defaultLighting: "Soft directional light from camera-right, controlled fill, catchlight in jewelry",
    poseFamily: "Portrait static",
    bodyDirection: "Square to camera, shoulders relaxed and slightly dropped",
    handBehavior: "Hands below frame or resting at sides; never near face or ears",
    legBehavior: "Not visible in frame",
    headDirection: "Straight to camera, chin neutral, both ears visible",
    realismNotes:
      "Highly reliable for Higgsfield. Clean portrait with minimal hand rendering. Watch for: earring symmetry, chain rendering against skin, natural ear attachment.",
    whyItWorks:
      "A clean portrait hero gives buyers immediate visibility of jewelry scale, sparkle, and placement against the face and neck, the primary context for purchase decisions.",
    deltaBlueprint:
      "Override framing to half-body portrait, shoulders up. Camera at eye level, ~2m, straight on. Model faces camera, chin neutral, both ears visible. Hands below frame. Soft directional light with catchlight on {item}. Product is the focal point against clean skin. No rotation, no crop below chest.",
  },

  // ────────────────────────────────────────────
  // 23. three_quarter_ear_reveal
  // ────────────────────────────────────────────
  {
    id: "three_quarter_ear_reveal",
    title: "Three-Quarter Ear Reveal",
    role: "Angled portrait showing earring dimension, profile of the ear, and jawline context.",
    shotCategory: "product_focus",
    suitableFamilies: ["jewelry"],
    suitableItems: ["earrings", "earring", "ear cuff", "drop earring", "hoop", "stud"],
    suitableGoals: ["product_clarity", "detail_focus", "premium_branding"],
    suitableStyles: ["commercial", "luxury", "editorial", "minimal", "contemporary"],
    suitableGenderPresentation: ["womenswear", "unisex"],
    creativityBand: ["safe", "balanced"],
    logoVisibilitySuitability: "high",
    productClaritySuitability: "high",
    silhouetteSuitability: "low",
    detailSuitability: "high",
    movementSuitability: "low",
    editorialStrength: "medium",
    higgsfieldReliability: "high",
    difficulty: "easy",
    logoRisk: "low",
    anatomyRisk: "low",
    occlusionRisk: "low",
    bestUsedWhen:
      "The hero is an earring and you need a second angle showing how it sits against the ear, jawline, and neck from a three-quarter view.",
    avoidWhen: "The product is not worn on the ear, or the set already has a profile shot.",
    defaultFraming: "Close portrait, face and neck area, slight negative space on the ear side",
    defaultLens: "85mm",
    defaultAperture: "f/2.8",
    defaultCameraHeight: "eye level",
    defaultCameraDistance: "~1.5m",
    defaultAngle: "30-40 degrees from front, camera-side toward the featured ear",
    defaultLighting: "Key light from the ear side to illuminate the earring, soft fill from opposite side",
    poseFamily: "Portrait angled",
    bodyDirection: "Head turned 30-40 degrees away from camera, exposing the near ear fully",
    handBehavior: "Not in frame; avoid touching ear or hair near the earring",
    legBehavior: "Not visible in frame",
    headDirection: "Turned away from camera 30-40 degrees, chin slightly lifted to elongate the neck",
    realismNotes:
      "Three-quarter portraits are reliable for Higgsfield. Watch for: earring attachment point to ear lobe, earring scale relative to ear, hair not merging with the earring. Keep hair behind the ear on the featured side.",
    whyItWorks:
      "A three-quarter angle reveals the earring's dimension, drop length, and how it catches light, things a front-on shot cannot fully show. The jawline and neck provide scale context.",
    deltaBlueprint:
      "Shift camera 30-40 degrees toward the featured ear. Model turns head away from camera, chin slightly up, exposing the near ear fully. Hair swept behind the featured ear. Key light from the ear side to catch {item} reflections. Tight portrait crop, face and neck. f/2.8 for shallow depth isolating the earring.",
  },

  // ────────────────────────────────────────────
  // 24. profile_jewelry_focus
  // ────────────────────────────────────────────
  {
    id: "profile_jewelry_focus",
    title: "Profile Jewelry Focus",
    role: "Full profile showing earring silhouette against the jawline and neck.",
    shotCategory: "detail",
    suitableFamilies: ["jewelry"],
    suitableItems: ["earrings", "earring", "ear cuff", "drop earring", "hoop", "stud", "necklace"],
    suitableGoals: ["detail_focus", "product_clarity", "silhouette"],
    suitableStyles: ["luxury", "editorial", "minimal", "contemporary", "commercial"],
    suitableGenderPresentation: ["womenswear", "unisex"],
    creativityBand: ["balanced", "directional"],
    logoVisibilitySuitability: "medium",
    productClaritySuitability: "high",
    silhouetteSuitability: "high",
    detailSuitability: "high",
    movementSuitability: "low",
    editorialStrength: "high",
    higgsfieldReliability: "medium",
    difficulty: "moderate",
    logoRisk: "low",
    anatomyRisk: "low",
    occlusionRisk: "low",
    bestUsedWhen:
      "The earring has a distinctive silhouette, drop length, or shape that reads best in profile. Also strong for necklaces that drape along the collarbone.",
    avoidWhen: "The earring is a small stud with no visible silhouette. Also avoid if the set already has two profile-angle shots.",
    defaultFraming: "Tight portrait, ear to shoulder, profile crop with negative space behind the earring",
    defaultLens: "85mm",
    defaultAperture: "f/2.8",
    defaultCameraHeight: "eye level",
    defaultCameraDistance: "~1.5m",
    defaultAngle: "90 degrees, full profile, camera perpendicular to the ear",
    defaultLighting: "Backlight or rim light to separate earring from background, soft key from camera side",
    poseFamily: "Profile portrait",
    bodyDirection: "Full profile, model facing perpendicular to camera",
    handBehavior: "Not in frame",
    legBehavior: "Not visible in frame",
    headDirection: "Straight profile, chin slightly lifted, neck elongated",
    realismNotes:
      "Profile shots are moderately reliable. Watch for: ear anatomy rendering, earring connection to lobe, hair not overlapping the earring. Rim lighting can create unnatural glow around small metal pieces.",
    whyItWorks:
      "A clean profile isolates the earring's silhouette against negative space, letting buyers see the exact shape, drop, and movement of the piece against the jawline.",
    deltaBlueprint:
      "Camera at 90-degree profile. Model faces perpendicular to lens, chin slightly lifted, neck elongated. Hair fully behind the ear. Rim light or backlight to separate {item} silhouette from background. Tight crop, ear to shoulder. f/2.8 for shallow depth. The earring's outline against skin and negative space is the entire composition.",
  },

  // ────────────────────────────────────────────
  // 25. ear_detail_crop
  // ────────────────────────────────────────────
  {
    id: "ear_detail_crop",
    title: "Ear Detail Crop",
    role: "Extreme close-up on the ear showing earring construction, stone detail, and metal finish.",
    shotCategory: "detail",
    suitableFamilies: ["jewelry"],
    suitableItems: ["earrings", "earring", "ear cuff", "drop earring", "hoop", "stud"],
    suitableGoals: ["detail_focus", "premium_branding"],
    suitableStyles: ["luxury", "commercial", "editorial", "minimal"],
    suitableGenderPresentation: ["womenswear", "unisex"],
    creativityBand: ["safe", "balanced"],
    logoVisibilitySuitability: "high",
    productClaritySuitability: "high",
    silhouetteSuitability: "low",
    detailSuitability: "high",
    movementSuitability: "low",
    editorialStrength: "low",
    higgsfieldReliability: "medium",
    difficulty: "moderate",
    logoRisk: "low",
    anatomyRisk: "low",
    occlusionRisk: "low",
    bestUsedWhen:
      "The earring has fine detail, gemstones, engravings, or textured metalwork that needs magnification to appreciate.",
    avoidWhen: "The earring is a simple plain stud with no visible detail at close range.",
    defaultFraming: "Extreme close-up, just the ear and earring, earring filling 60-70% of frame",
    defaultLens: "85mm (or macro-equivalent crop)",
    defaultAperture: "f/2.8",
    defaultCameraHeight: "ear level",
    defaultCameraDistance: "~0.8m",
    defaultAngle: "Slight three-quarter toward the ear, 15-20 degrees off profile",
    defaultLighting: "Focused directional key to catch gemstone sparkle and metal reflections, minimal fill",
    poseFamily: "Detail static",
    bodyDirection: "Only ear and surrounding skin visible",
    handBehavior: "Not in frame",
    legBehavior: "Not visible in frame",
    headDirection: "Turned to present the ear, but head is mostly out of frame",
    realismNotes:
      "Extreme close-ups push AI rendering. Watch for: lobe attachment detail, clasp rendering, stone facet reflections, metal colour consistency. May need 2-3 generations for clean detail.",
    whyItWorks:
      "A detail crop lets buyers examine the craftsmanship, stone quality, and finish that they would inspect in a store. It replaces the logo-crop archetype for jewelry that has no visible text branding.",
    deltaBlueprint:
      "Extreme close-up on the ear zone. {item} fills 60-70% of the frame. Camera at ear level, ~0.8m, angled 15-20 degrees off profile. Focused directional light to catch sparkle and metal finish. Only ear, skin, and the piece are visible. f/2.8 for shallow depth. This is the craftsmanship validation shot.",
  },

  // ────────────────────────────────────────────
  // 26. mood_portrait_jewelry
  // ────────────────────────────────────────────
  {
    id: "mood_portrait_jewelry",
    title: "Mood Portrait with Jewelry",
    role: "Editorial portrait with visible jewelry, creating brand mood while keeping product readable.",
    shotCategory: "editorial",
    suitableFamilies: ["jewelry", "eyewear"],
    suitableItems: ["earrings", "earring", "ear cuff", "necklace", "pendant", "choker", "sunglasses"],
    suitableGoals: ["mood", "styling_story", "premium_branding"],
    suitableStyles: ["editorial", "luxury", "contemporary", "minimal", "resort"],
    suitableGenderPresentation: ["womenswear", "unisex"],
    creativityBand: ["balanced", "directional"],
    logoVisibilitySuitability: "medium",
    productClaritySuitability: "medium",
    silhouetteSuitability: "low",
    detailSuitability: "medium",
    movementSuitability: "low",
    editorialStrength: "high",
    higgsfieldReliability: "medium",
    difficulty: "moderate",
    logoRisk: "low",
    anatomyRisk: "low",
    occlusionRisk: "medium",
    bestUsedWhen:
      "The set needs an editorial mood shot that still shows the jewelry. Combines atmosphere and product visibility for social media or opening spreads.",
    avoidWhen: "Product clarity is the only goal and every shot must be product-first. Also avoid if the set is 3 shots or fewer.",
    defaultFraming: "Half body or chest-up, with environmental or tonal backdrop",
    defaultLens: "85mm",
    defaultAperture: "f/2.8",
    defaultCameraHeight: "eye level or slightly above",
    defaultCameraDistance: "~2m",
    defaultAngle: "Slight angle, 10-20 degrees, for depth and mood",
    defaultLighting: "Atmospheric directional light, golden hour or controlled studio, intentional shadow play",
    poseFamily: "Editorial portrait",
    bodyDirection: "Slight turn or lean, relaxed and editorial",
    handBehavior: "Away from face and jewelry; may rest on shoulder or below frame",
    legBehavior: "Not visible in frame",
    headDirection: "Off-camera gaze or looking down, editorial mood angle",
    realismNotes:
      "Moderate difficulty due to atmospheric lighting. Watch for: jewelry visibility in low-light mood, earring not lost in shadow, catchlight on metal surfaces. May need adjusted lighting to balance mood and product clarity.",
    whyItWorks:
      "An editorial mood portrait elevates the jewelry from a product shot to a brand story, showing who the wearer is and the occasion the piece belongs to, while keeping the product visible.",
    deltaBlueprint:
      "Shift to editorial mood: atmospheric light, slight angle, off-camera gaze. Model relaxed, slight lean or turn. {item} visible and catching light despite the moodier setup. Hands away from the jewelry. Half-body or chest-up crop. The piece reads clearly but the mood tells the brand story.",
  },

  // ────────────────────────────────────────────
  // 27. pair_symmetry_validation
  // ────────────────────────────────────────────
  {
    id: "pair_symmetry_validation",
    title: "Pair Symmetry Validation",
    role: "Front-facing portrait showing both earrings for pair readability and symmetry confirmation.",
    shotCategory: "product_focus",
    suitableFamilies: ["jewelry"],
    suitableItems: ["earrings", "earring", "ear cuff", "hoop", "stud", "drop earring"],
    suitableGoals: ["product_clarity", "detail_focus"],
    suitableStyles: ["commercial", "luxury", "minimal", "contemporary"],
    suitableGenderPresentation: ["womenswear", "unisex"],
    creativityBand: ["safe", "balanced"],
    logoVisibilitySuitability: "high",
    productClaritySuitability: "high",
    silhouetteSuitability: "low",
    detailSuitability: "high",
    movementSuitability: "low",
    editorialStrength: "low",
    higgsfieldReliability: "high",
    difficulty: "easy",
    logoRisk: "low",
    anatomyRisk: "low",
    occlusionRisk: "low",
    bestUsedWhen:
      "Earrings are sold as a pair and the buyer needs to see both pieces matching. Essential for e-commerce where pair validation reduces returns.",
    avoidWhen: "The product is a single ear cuff or asymmetric pair (use profile shot instead).",
    defaultFraming: "Close portrait, face-on, both ears and jawline visible, cropped at collarbone",
    defaultLens: "85mm",
    defaultAperture: "f/4",
    defaultCameraHeight: "eye level",
    defaultCameraDistance: "~1.5m",
    defaultAngle: "Dead straight, 0 degrees, for symmetry comparison",
    defaultLighting: "Even, balanced lighting from both sides for symmetrical illumination of both earrings",
    poseFamily: "Portrait symmetrical",
    bodyDirection: "Perfectly square to camera",
    handBehavior: "Not in frame",
    legBehavior: "Not visible in frame",
    headDirection: "Straight to camera, chin neutral, ears exposed equally on both sides",
    realismNotes:
      "Highly reliable because of the simple, symmetrical setup. Watch for: earring size consistency between left and right, matching metal colour on both sides, symmetrical hair clearance from both ears.",
    whyItWorks:
      "A symmetrical front-on shot is the only way to prove the pair matches. It reduces purchase anxiety for e-commerce buyers who cannot inspect both earrings in person.",
    deltaBlueprint:
      "Dead-straight front portrait, 0-degree angle. Both ears fully visible, hair cleared from both sides. Even bilateral lighting for identical illumination on both {item}. Model faces camera squarely, chin neutral. Close crop at collarbone. This is a pair-validation shot: symmetry and matching are the priority.",
  },
];
